  name: eau_mineral
  description: A Slim mineral application.
  version: 0.0.1
  publish_to: none
  mineral:
    commands:
  environment:
    sdk: '>=3.3.0 <4.0.0'
  dependencies:
    mineral: ^4.0.0-dev.10
    mineral_cache: ^1.0.0-dev.3
  dev_dependencies:
    lints: ^2.0.0
    test: ^1.21.0
